### ISSUE TITLE
global: incompatible change released as patch version

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/dojson#142]
The change introduced in d3272c0b0e5cb2a62c801eb9f25a4a783940189f is a backward incompatible change (breaks code on Zenodo), so the change ought to have been release in a `v1.3.0` instead of `v1.2.1`. Just logging the issue here for completeness

**Comment by jirikuncar** [comment]
@lnielsen I'm sorry. This should have not been introduced in first place as it's not according to MARC21.

**Comment by tiborsimko** [comment]
OT1H it's not nice to introduce an incompatible change in the patchlevel release, OTOH dojson v1.2.0 clearly misinterpreted the MARC standard originally, so that  d3272c0b0e5cb2a62c801eb9f25a4a783940189f could be considered a bug fix that has its place in the patchlevel release...

**Comment by egabancho** [comment]
@lnielsen I'm sorry too. As @tiborsimko mentioned I considered it as a bug fix because according to MARC21 is a non-repeatable field https://www.loc.gov/marc/bibliographic/bd100.html
