### ISSUE TITLE
utils: force_list returns a tuple

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/dojson#154]
`utils.force_list()`, despite its name and docstring, actually returns a `tuple` or `None`.

A better implementation could be:

``` python

def force_list(data):
    """Wrap data in list."""
    if data is None:
        return []
    elif not isinstance(data, (list, tuple, set)):
        return [data]
    elif isinstance(data, (tuple, set)):
        return list(data)
    return data
```

however then it would be necessary to amend `filter_values` to also filter away empty lists.

**Comment by jirikuncar** [comment]
IMHO it should not be necessary to make list from tuple and set. Can you provide a code snippet where the current code is causing troubles?

**Comment by kaplun** [comment]
It's not really trouble, but more a semantic issue where the name of the function doesn't correspond to its behavior.

In particular, see : https://github.com/inspirehep/inspire-next/pull/1070/files#diff-2dffa3ace57cdc6c5dabaa1d20b1fe6cR87

**Comment by kaplun** [comment]
As reported in https://github.com/inveniosoftware/dojson/pull/155#discussion_r70614422 finally the best solution is just to amend the docstring.

**Comment by blixhavn** [comment]
What's the conclusion on this? Do we make a PR to amend the docstring?

**Comment by kaplun** [comment]
In INSPIRE we have implemented a util called `force_force_list()`:
https://github.com/inspirehep/inspire-next/blob/master/inspirehep/utils/helpers.py#L68

So IMHO it's OK to go either way.
