### ISSUE TITLE
RFC is 'Undo' still experimental 

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/dojson#194]
Due to https://github.com/inveniosoftware/dojson/blob/master/dojson/contrib/to_marc21/model.py#L21 we get the following warnings:
```
.../dojson/contrib/to_marc21/model.py:21: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
```

Is this feature still experimental? Should we remove the warning? I see that it's used on Zenodo:
https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/to_marc21/model.py#L33
and on CDS it was recently removed:
https://github.com/CERNDocumentServer/cds-dojson/commit/0e51c3209776c3fbb2fa131b9c6463d293913855#diff-6769d5bc9abff7a2879ee1c4395cda20

@lnielsen @egabancho WDYT?

**Comment by lnielsen** [comment]
Let's remove the warning. It's used in extensively in production and it might be that it will need changes in the future, but it's not helpful to see the error message every single time you run. The same can be singled in the documentation and via version numbers.

**Comment by egabancho** [comment]
cc @blixhavn

**Comment by blixhavn** [comment]
I agree with Lars. We've never had any problems with the undo feature (sorry about the delay, I was on vacation).
