### ISSUE TITLE
 marc21: add field definitions for holdings records 

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/dojson#21]
Please add holding fields as well: http://www.loc.gov/marc/holdings/.  In brief, they describe either the physical location and conditions of the documents, and the holdings of the periodicals (which issues do we have of a journal).

**Comment by aw-bib** [comment]
There was a recent discussion in the context of `bibcirculation` 2.x on a preliminary set of fields to use.

**Comment by aw-bib** [comment]
@mvesper I think this issue is the missing link from our discussion on invenio-circulation. Bascially, you json schema should just use these guys (cf. our discussions with @agentilb and  @tbasaglia)

cc @tiborsimko

**Comment by egabancho** [comment]
@jirikuncar Should this be moved to [invenio-circulation](https://github.com/inveniosoftware/invenio-circulation)?

**Comment by fjorba** [comment]
There is a reason for moving it to invenio-circulation for describing items, but only for tags describing items (like 852), but do not forget that those records also describe journals and periodicals (mainly 866).  The requisites of both type of tags are quite different.

Also probably the sites have different needs.  For example, at UAB, we do have lots of 866 holding records at DDD, because we link the journal to the (digital) articles (a single example: http://ddd.uab.cat/record/106630).  For the Catalan musical manuscripts catalog, we do use 852 to describe where a particular manuscript is kept (for example: http://ifmuc.uab.cat/record/2155).

However, we don't plan to use circulation in neither site.

**Comment by aw-bib** [comment]
@egabancho / @jirikuncar I placed it here as @mvesper was not aware of the fact that his work is actually related to `doJSON()`. @mvesper has already some stuff but it should end up here in the holdings block.

**Comment by aw-bib** [comment]
@fjorba you do not have to use circulation for the items. Basically, can treat them as _reference_ so those are not for loan. OTOH would make some sense that stuff you have _can_ show up on the upcoming holdings tab, right? (Similar for the articles linked to a journal.) Whether you display that one is again another story.

What we are heading for in the discussions with @agentilb and @tbasaglia is mainly to move holdings curation to the place it belongs beyond some basically inaccessible internal tables.

BTW: right now @mvesper only has fields for book-like holdings. So nothing 866ish. Still, even if parts get filled and thus help to solve this issue it would be great.

**Comment by jirikuncar** [comment]
Thanks to #33 (@egabancho) it's possible to easily extend `dojson.contrib.marc21` with additional rules. Hence we should close the discussion here and move it to `invenio-circulation` as proposed in https://github.com/inveniosoftware/dojson/issues/21#issuecomment-147073952.

**Comment by aw-bib** [comment]
I think, however, that Marc Holdings structure should be integral part of the marc21 schema.

**Comment by jirikuncar** [comment]
@aw-bib we can have a sprint on extracting information from http://www.loc.gov/marc/holdings/ using https://github.com/jirikuncar/marc-json-schema/tree/generator.
