### ISSUE TITLE
marc21: generate "undo" functions

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/dojson#27]
- [x] generate "undo" function for _json2marc21_
- [x] shall we generate it in the same files or new one?
  - pros: easier to maintain
  - cons: large files, slower loading
## 

cc @tiborsimko @jmartinm

**Comment by jmartinm** [comment]
For an example of how it would look like in one file, see the [INSPIRE repo](https://github.com/inspirehep/inspire-next/tree/master-elasticsearch/inspire/dojson/hep/fields)

For us, having it into one file for easier maintenance seems to make sense.

**Comment by egabancho** [comment]
shall we closed this issue? I think it was done here 562bd423a60ee8adafb8b16549fcf4a13bab46d7 by @Theer108

**Comment by jirikuncar** [comment]
closed via 562bd423a60ee8adafb8b16549fcf4a13bab46d7
