### ISSUE TITLE
marc21: validate field names

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/dojson#6]

**Comment by tiborsimko** [comment]
@aw-bib Can you please look at files like:
- https://github.com/inveniosoftware/dojson/blob/master/dojson/contrib/marc21/fields/bd4xx.py

in this place:
- https://github.com/inveniosoftware/dojson/tree/master/dojson/contrib/marc21/fields

to see if the descriptive MARC field/subfield names (such as `date_of_a_work`) look generally OK?

(They were basically taken literally from [MARC Bibilographic](http://www.loc.gov/marc/bibliographic/) standard and massaged a bit to eliminate dots, parentheses, "etc", and more.)

Please let us know if something is to be changed.

**Comment by tiborsimko** [comment]
Closing the issue due to inactivity.  Note that DoJSON 1.0 was already released. @aw-bib @fjorba @Kennethhole If you spot any problem with extracted field names, please just restart a new issue.
