### ISSUE TITLE
dojson: test all fields

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/dojson#79]
Make sure all the fields are tested. This can be split between many people.
Checked fields:
- [ ] bd00x.py
- [ ] bd01x09x.py
- [ ] bd1xx.py
- [ ] bd20x24x.py
- [ ] bd25x28x.py
- [ ] bd3xx.py
- [ ] bd4xx.py
- [ ] bd5xx.py
- [ ] bd6xx.py
- [ ] bd70x75x.py
- [ ] bd76x78x.py - @SamiHiltunen 
- [ ] bd80x83x.py
- [ ] bd84188x.py

... (TODO: Check the file names and finish the list)

**Comment by jirikuncar** [comment]
Closed via 4dbe7bb32f66d1a964a3c81655b6e2216eb84e9d.
