### ISSUE TITLE
Write tests to JSON Schema

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/dojson#84]
**What we want**: Make sure that the JSON schema generated by DoJSON correctly matches the fields from the MARC21 test files. We don't want to miss any field.

**Problem**: JSON Schema's `additionalProperties` [is currently limited](http://spacetelescope.github.io/understanding-json-schema/reference/combining.html#allof) when used with `allOf` or `anyOf`. Thus we cannot use the JSON Schema as it is to validate that any additional fields have been added.

**Note**: Currently all the fields are typed as `string`. Thus we don't want to test complex typing or formats.

**Possible solution 1**: Write a script which checks that all fields in a JSON MARC21 (JSON generated by dojson with a MARC21 file as input) are present in the JSON Schema.

**Possible solution 2**: Write a script which transforms a JSON Schema in a standardized way by merging all the schemas from `anyOf` lists, then add `additionalProperties = false` and use a JSON Schema library to validate.

**Possible solution 3**: Use the domapping tool to generate mappings from JSON Schema. Add `strict` everywhere in the mapping to refuse additional fields. Send the mappings to Elasticsearch. Try to load the MARC21 files and see if it fails.

**Comment by switowski** [comment]
Either check if after importing data to ElasticSearch all data from MARCXML appears in ES or compare the MARCXML data with JSON schema and see if we are missing any fields.

:+1: for the second solution

**Comment by tiborsimko** [comment]
Notes from live debate: now that MARC21 schemas are removed from `dojson` package to `invenio-marc21` package, this kind of testing may not fully belong here. What about creating a new package called `doschema` that could perform various schema-related checks and utility functions?  E.g. expand sub-schemas on the backend side, e.g. check compatibilities between schema versions (fields added/removed, defitinions modified), etc.

**Comment by nharraud** [comment]
@tiborsimko Ok, can you create the inveniosoftware repository please? I don't have the permissions and @Paulina1 already started working on the schema backward compatibility check.

**Comment by tiborsimko** [comment]
Done, you can now clone the repository:
- https://github.com/inveniosoftware/doschema

BTW, we could perhaps think of using this repository for some Marshmallow  <-> JSON Schema synchronisation as well, if we shall keep on using [Marshmallow](http://marshmallow.readthedocs.org/en/latest/) for some publicly consumable JSON exports... CC @lnielsen

**Comment by jirikuncar** [comment]
JSONSchemas have been moved back.

**Comment by jirikuncar** [comment]
Good tests came via #143.
